name: "Coverity"

on:
  workflow_dispatch

jobs:
  build:
    runs-on: Ubuntu-Latest
    container:
      image: fcbrbrazil/coverity:2022.6.0
      credentials:
        username: fcbrbrazil
        password: ${{ secrets.docker_hub_password}}
    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    # Perform Static Analysis
    - name: Polaris (SAST)
      run: |
        apt update
        apt install -y zip
        curl -s "https://get.sdkman.io" | bash
        source "/root/.sdkman/bin/sdkman-init.sh"
        cd /root/.sdkman/bin/
        chmod +x sdkman-init.sh
        sdk version
        sdk install kotlin
        cov-build --dir idir --fs-capture-search . kotlinc .
        cov-analyze --dir idir --all --webapp-security --enable-audit-mode
